# Generated by Django 6.0.2 on 2026-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_communityphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
