# Generated by Django 6.0.2 on 2026-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dish_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cultural_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='preparation_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
